### ISSUE TITLE
List of Pull Requests/Committs from Percy

### ISSUE THREAD

**Issue by NaimSantos** [Gideon9212/Script-MainServer#2]
A list to check the availability of the pull requests open in Percy's Live20117Link repository compared to this repository:
- [ ] Ygoproco/Live2017Links#746
- [x] Ygoproco/Live2017Links#765
- [x] Ygoproco/Live2017Links#771
- [x] Ygoproco/Live2017Links#772
- [x] Ygoproco/Live2017Links#773
- [x] Ygoproco/Live2017Links#775
- [x] Ygoproco/Live2017Links#776
- [x] Ygoproco/Live2017Links#777
- [x] Ygoproco/Live2017Links#778
